name: update profile

on:
  schedule:
    - cron: '0 */2 * * *' # 每 2 小时执行一次
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ 生成 Snake SVG（支持私有仓库提交/PR/Issue）
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.MY_PAT }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
          args: '--include-pulls --include-issues'

      # 3️⃣ 推送 Snake SVG 到 assets 分支根目录
      - name: Push Snake to assets branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_PAT }}
          publish_branch: assets
          publish_dir: .
          force_orphan: true
